name: AI Commit Message Generator

on:
  push:
    branches:
      - main

jobs:
  generate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run AI Commit Message Generator
        id: commit-message
        run: |
          output=$(node src/index.js | tr '\n' ' ' | tr -d '"')
          echo "COMMIT_MESSAGE=\"$output\"" >> $GITHUB_ENV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Print Commit Message
        run: |
          echo "AI Generated Commit Message: ${{ env.COMMIT_MESSAGE }}"

      - name: Post comment on commit
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const message = process.env.COMMIT_MESSAGE;
            const commit_sha = context.payload.head_commit.id;
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commit_sha,
              body: `### 💡 Suggested Commit Message:\n> ${message}\n\n_You can update your commit message to make it clearer!_ 🚀`
            });

